<?php
/**
 * Home Coffee Affiliate — functions.php
 *
 * Production-hardened for GeneratePress affiliate sites.
 * Generated by build_niche_themes.py for Home Coffee.
 *
 * GP RULES (verified from docs.generatepress.com + source):
 *   - GP auto-enqueues parent + child CSS. NEVER re-enqueue.
 *   - generate_sidebar_layout uses hyphens: 'no-sidebar', 'right-sidebar'
 *   - generate_show_title requires boolean false, not string
 *   - generate_before_header priority 7 = after skip link, before header
 *   - Header ID is #masthead (NOT #site-header)
 *   - generate_page_builder_class does NOT exist — use generate_page_class
 */


// =============================================================
// 1. IMAGE OPTIMIZATION
// =============================================================

// 1a. Remove unused auto-generated image sizes (saves disk per upload)
function aff_remove_unused_image_sizes() {
    remove_image_size( '1536x1536' );
    remove_image_size( '2048x2048' );
}
add_action( 'init', 'aff_remove_unused_image_sizes' );

// 1b. Limit big image scaling — affiliate sites don't need 2560px originals
add_filter( 'big_image_size_threshold', function() {
    return 1200; // 1200px max width — enough for content + retina
} );

// 1c. JPEG quality — 82 is fine for affiliate product images
add_filter( 'jpeg_quality', function() {
    return 82;
} );

// 1d. Smart lazy loading — eager for first (LCP) image, lazy for rest
function aff_smart_lazy_loading( $attr, $attachment, $size ) {
    static $count = 0;
    $count++;
    if ( $count <= 1 ) {
        $attr['fetchpriority'] = 'high';
        $attr['loading']       = 'eager';
    } else {
        $attr['loading']  = 'lazy';
        $attr['decoding'] = 'async';
    }
    return $attr;
}
add_filter( 'wp_get_attachment_image_attributes', 'aff_smart_lazy_loading', 10, 3 );

// 1e. Async decode all content images (improves INP)
function aff_async_decode_content_images( $content ) {
    if ( is_admin() ) return $content;
    return preg_replace(
        '/<img(?![^>]*\bdecoding\b)([^>]*)>/i',
        '<img decoding="async"$1>',
        $content
    );
}
add_filter( 'the_content', 'aff_async_decode_content_images', 99 );

// 1f. Responsive image sizes for content
function aff_content_image_sizes( $sizes, $size ) {
    if ( isset( $size[0] ) && $size[0] >= 800 ) {
        $sizes = '(max-width: 767px) 100vw, (max-width: 980px) 75vw, 50vw';
    }
    return $sizes;
}
add_filter( 'wp_calculate_image_sizes', 'aff_content_image_sizes', 10, 2 );


// =============================================================
// 2. PERFORMANCE — Remove WP bloat
// =============================================================

// 2a. Disable WordPress emojis (saves 2 requests + ~15KB per page)
function aff_disable_emojis() {
    remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
    remove_action( 'admin_print_scripts', 'print_emoji_detection_script' );
    remove_action( 'wp_print_styles', 'print_emoji_styles' );
    remove_action( 'admin_print_styles', 'print_emoji_styles' );
    remove_filter( 'the_content_feed', 'wp_staticize_emoji' );
    remove_filter( 'comment_text_rss', 'wp_staticize_emoji' );
    remove_filter( 'wp_mail', 'wp_staticize_emoji_for_email' );
    add_filter( 'emoji_svg_url', '__return_false' );
}
add_action( 'init', 'aff_disable_emojis' );

// 2b. Remove query strings from static resources (better CDN caching)
function aff_remove_query_strings( $src ) {
    if ( strpos( $src, '?ver=' ) !== false ) {
        $src = remove_query_arg( 'ver', $src );
    }
    return $src;
}
add_filter( 'style_loader_src', 'aff_remove_query_strings', 10 );
add_filter( 'script_loader_src', 'aff_remove_query_strings', 10 );

// 2c. Remove unnecessary head junk
remove_action( 'wp_head', 'wp_generator' );           // WP version (security)
remove_action( 'wp_head', 'rsd_link' );                // Really Simple Discovery
remove_action( 'wp_head', 'wlwmanifest_link' );        // Windows Live Writer
remove_action( 'wp_head', 'wp_shortlink_wp_head' );    // Shortlinks
remove_action( 'wp_head', 'rest_output_link_wp_head' ); // REST API link
remove_action( 'wp_head', 'wp_oembed_add_discovery_links' ); // oEmbed
remove_action( 'wp_head', 'feed_links_extra', 3 );     // Extra feed links

// 2d. Disable comments entirely (affiliate sites don't use them)
// Comments are also disabled in build-golden-template.sh, but this is belt+suspenders
function aff_disable_comments_completely() {
    // Close comments on all post types
    add_filter( 'comments_open', '__return_false', 20, 2 );
    add_filter( 'pings_open', '__return_false', 20, 2 );
    // Hide existing comments
    add_filter( 'comments_array', '__return_empty_array', 10, 2 );
    // Remove comment support from post types
    remove_post_type_support( 'post', 'comments' );
    remove_post_type_support( 'page', 'comments' );
}
add_action( 'init', 'aff_disable_comments_completely' );

// 2e. Remove comment-related admin menu items
function aff_remove_comments_admin() {
    remove_menu_page( 'edit-comments.php' );
    remove_submenu_page( 'options-general.php', 'options-discussion.php' );
}
add_action( 'admin_menu', 'aff_remove_comments_admin' );

// 2f. Remove comments from admin bar
function aff_remove_comments_admin_bar( $wp_admin_bar ) {
    $wp_admin_bar->remove_node( 'comments' );
}
add_action( 'admin_bar_menu', 'aff_remove_comments_admin_bar', 999 );

// 2g. Preload GP icon font (prevents CLS from icon rendering)
function aff_preload_gp_font() {
    $gp_font = get_template_directory_uri() . '/fonts/generatepress.woff2';
    echo '<link rel="preload" href="' . esc_url( $gp_font ) . '" as="font" type="font/woff2" crossorigin>' . "\n";
}
add_action( 'wp_head', 'aff_preload_gp_font', 2 );


// =============================================================
// 3. SECURITY
// =============================================================

// 3a. Disable XML-RPC (prevents brute force via xmlrpc.php)
add_filter( 'xmlrpc_enabled', '__return_false' );

// 3b. Add security attributes to external links
function aff_external_link_security( $content ) {
    return preg_replace_callback(
        '/<a\s+([^>]*href=["\']https?:\/\/(?!(?:localhost|' . preg_quote( wp_parse_url( home_url(), PHP_URL_HOST ), '/' ) . '))[^"\']+["\'][^>]*)>/i',
        function ( $matches ) {
            $attrs = $matches[1];
            if ( strpos( $attrs, 'target=' ) === false ) {
                $attrs .= ' target="_blank"';
            }
            if ( strpos( $attrs, 'rel=' ) === false ) {
                $attrs .= ' rel="noopener noreferrer"';
            }
            return '<a ' . $attrs . '>';
        },
        $content
    );
}
add_filter( 'the_content', 'aff_external_link_security' );

// 3c. Disable file editing in WP admin (defense-in-depth, also in wp-config)
if ( ! defined( 'DISALLOW_FILE_EDIT' ) ) {
    define( 'DISALLOW_FILE_EDIT', true );
}


// =============================================================
// 4. SEO & AFFILIATE
// =============================================================

// 4a. Auto-add affiliate disclosure to top of all posts
function aff_auto_disclosure( $content ) {
    if ( ! is_singular( 'post' ) || ! in_the_loop() || ! is_main_query() ) {
        return $content;
    }

    $disclosure = '<div class="affiliate-disclosure">'
        . '<strong>Disclosure:</strong> As an Amazon Associate I earn from qualifying purchases. '
        . 'This post may contain affiliate links at no extra cost to you.'
        . '<br><small>Reviewed by Marco DeLuca</small>'
        . '</div>';

    return $disclosure . $content;
}
add_filter( 'the_content', 'aff_auto_disclosure', 5 ); // priority 5 = before content filters

// 4b. Breadcrumbs via Rank Math (GP hook: generate_before_content)
function aff_add_breadcrumbs() {
    if ( ! is_front_page() && function_exists( 'rank_math_the_breadcrumbs' ) ) {
        echo '<div class="aff-breadcrumbs" style="margin-bottom:1em;font-size:0.85em;color:#64748b;">';
        rank_math_the_breadcrumbs();
        echo '</div>';
    }
}
add_action( 'generate_before_content', 'aff_add_breadcrumbs', 5 );

// 4c. Add structured data for affiliate articles (WebPage + BreadcrumbList handled by Rank Math)
// This adds the "last modified" meta for freshness signals
function aff_add_article_modified_time() {
    if ( is_singular( 'post' ) ) {
        echo '<meta property="article:modified_time" content="' . esc_attr( get_the_modified_time( 'c' ) ) . '">' . "\n";
    }
}
add_action( 'wp_head', 'aff_add_article_modified_time', 5 );


// =============================================================
// 5. GP LAYOUT CONTROLS
// =============================================================

// 5a. Sidebar layout — right sidebar on posts, no sidebar on pages
add_filter( 'generate_sidebar_layout', function( $layout ) {
    if ( is_page() ) {
        return 'no-sidebar';
    }
    return 'right-sidebar'; // default for posts + archives
} );

// 5b. Remove page title on homepage
add_filter( 'generate_show_title', function( $show ) {
    if ( is_front_page() ) {
        return false; // boolean false required
    }
    return $show;
} );


// =============================================================
// 6. DATABASE OPTIMIZATION
// =============================================================

// 6a. Limit post revisions (affiliate sites generate many drafts via WXR import)
if ( ! defined( 'WP_POST_REVISIONS' ) ) {
    define( 'WP_POST_REVISIONS', 3 );
}

// 6b. Increase autosave interval
if ( ! defined( 'AUTOSAVE_INTERVAL' ) ) {
    define( 'AUTOSAVE_INTERVAL', 300 ); // 5 minutes
}


// =============================================================
// 7. HOMEPAGE
// =============================================================

// 7a. Enqueue homepage CSS only on front page
function aff_homepage_styles() {
    if ( is_front_page() ) {
        wp_enqueue_style(
            'aff-homepage',
            get_stylesheet_directory_uri() . '/homepage.css',
            array( 'generate-style' ),
            filemtime( get_stylesheet_directory() . '/homepage.css' )
        );
    }
}
add_action( 'wp_enqueue_scripts', 'aff_homepage_styles' );

// 7b. Remove GP content wrapper on homepage template (full-width sections)
function aff_homepage_full_width( $classes ) {
    if ( is_page_template( 'template-homepage.php' ) ) {
        $classes[] = 'full-width-content';
    }
    return $classes;
}
add_filter( 'body_class', 'aff_homepage_full_width' );

// 7c. Remove the default entry-header on homepage template
function aff_hide_homepage_title( $show ) {
    if ( is_page_template( 'template-homepage.php' ) ) {
        return false;
    }
    return $show;
}
add_filter( 'generate_show_title', 'aff_hide_homepage_title' );
